repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
    # local stuff
-   repo: local
    hooks:
    -   id: run-tests
        name: run tests
        entry: pytest warp-lane-server/tests
        stages: [push]
        language: python
        additional_dependencies: [pre-commit, pytest]
        always_run: true
        pass_filenames: false
