name: warp-lane-server
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - bcrypt
  - dateutils
  - psycopg2
  - sanic
  - sanic-cors
  - requests
  - pytest
  - pip
  - pip:
      - -e .
